PER-250 bugfix in submission clone handler
kineticdata/peripherals-kinetic-platform pull request #46
Opened 2022-01-11 21:10 UTC by ChadRehmKineticData

While fixing the bug also updated the variables to all be snake case.

2022-01-28 16:32 UTC, ChadRehmKineticData commented
The bug was a variable that was not defined submission_id

2022-01-31 17:29 UTC, jackboespflug requested changes

2022-01-31 17:29 UTC, jackboespflug commented on handlers/kinetic_request_ce_submission_clone_v1/handler/init.rb
>      end
You are chomping the trailing "/" in the else clauses, but not the if clause.

```
server = @info_values['api_server'].chomp("/")
if @server.include?("${space}")
  server = server.gsub("${space}", space_slug)
elsif !space_slug.to_s.empty?
  server = "#{server}/#{space_slug}"
end
```

2022-01-31 17:29 UTC, jackboespflug commented on handlers/kinetic_request_ce_submission_clone_v1/handler/init.rb
> +        json[:values] = orig_values.empty? ? {} : orig_values
This is such a weird pattern:

```
data = {}
data.tap do |json|
  ...
end
```

Why not just build the hash when creating it?
```
data = {
  :currentPage => {...},
  :coreState => ...
}
```

2022-02-21 14:31 UTC, jackboespflug approved these changes

2022-02-21 14:31 UTC, merged